name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js '18.x'
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run export
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.pages_pat }}
        BRANCH: gh-pages
        FOLDER: __sapper__/export/